# Default values for backbee.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


#create separate namespace for all objects
namespace:
  enabled: false
  create: false
  name: default #this will change url and app will be reachable under https://tester.default.example.com

#number of pods
replicaCount: 1

name: tester #if no namespace used app will be reachable under https://tester.example.com
domain: example.com


image:
  repository: gcr.io/google_containers
  application: echoserver
  tag: 1.8
  pullPolicy: IfNotPresent

#container:
#  ports:
#  - containerPort: 8080
#  - containerPort: 80
#    protocol: TCP
#  port: 8080 #deprecated
#  configVolumes: #already existing configmap named test-config with file test.txt inside
#  - name: test-config
#    mountPath: /etc/test
#    file: test.txt
#  pvcVolumes: #already existing PersistentVolumeClaim named test-disk
#  - name: test-vol
#    mountPath: /opt/test-disk
#    claimName: test-disk

#service:
#  type: NodePort
#  ports:
#  - port: 80
#    targetPort: 8080
#  - port: 82
#    targetPort: 81
#    protocol: TCP
#  port: 80 #deprecated


ingress:
  enabled: true
  annotations: {}
  class: nginx #this is value of controller.ingressClass from nginx-ingress chart deployed. It also requires
  paths:
  - path: "/"
    servicePort: 80
#  - path: "/test1/"

#envs:
#- name: ENV_NAME_1
#  value: "env-value-1"
#- name: ENV_NAME_2
#  value: "env-value-2"

#paths: #deprecated
#- "/app/"
#- "/health"

#configVolumes: #deprecated
#- name: test2-config
#  mountPath: /etc/test2
#  file: test2.txt
#
#pvcVolumes: #deprecated
#- name: test2-vol
#  mountPath: /opt/test2-disk
#  claimName: test2-disk

#additionalLabels: #additional labels to be added to deployment, pod, service and ingress
#- key: key1
#  value: value1