# Default values for backbee.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: tester
domain: example.com


image:
  repository: gcr.io/google_containers
  application: echoserver
  tag: 1.8
  pullPolicy: IfNotPresent

container:
  port: 8080

service:
  type: NodePort
  port: 80

ingress:
  annotations: {}
  class: example