apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.name }}
{{- if .Values.namespace.enabled }}
  namespace: {{ .Values.namespace.name }}
{{- end }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          {{- if .Values.envs }}
          env:
          {{- range .Values.envs }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.configVolumes or .Values.pvcVolumes }}
          volumeMounts:
          {{- range .Values.configVolumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}/{{ .file }}
              subPath: {{ .file }}
          {{- end }}
          {{- range .Values.pvcVolumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
          {{- end }}
          {{- end }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.application }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
              protocol: TCP
      {{- if .Values.configVolumes or .Values.pvcVolumes }}
      volumes:
      {{- range .Values.configVolumes }}
        - name: {{ .name }}
          configMap:
            name: {{ .name }}
            items:
            - key: {{ .file }}
              path: {{ .file }}
      {{- end }}
      {{- range .Values.pvcVolumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .claimName }}
      {{- end }}
      {{- end }}