{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    name: {{ .Values.namespace.name }}
    {{- range .Values.additionalLabels }}
    {{ .key }}: {{ .value }}
    {{- end }}
{{- end -}}