apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
{{- if .Values.namespace.enabled }}
  namespace: {{ .Values.namespace.name}}
{{- end }}
  labels:
    app: {{ .Values.name }}
    {{- range .Values.additionalLabels }}
    {{ .key }}: {{ .value }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.port }}
    protocol: TCP
  selector:
    app: {{ .Values.name }}
